version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: counter-image:latest
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      CONNECTION_STRING: Host=db;Database=mydatabase;Username=myuser;Password=mypassword
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
